from setuptools import find_packages, setup

package_name = 'example_python'

setup(
    name=package_name,
    version='0.0.0',
    packages=find_packages(exclude=['test']),
    data_files=[
        ('share/ament_index/resource_index/packages',
            ['resource/' + package_name]),
        ('share/' + package_name, ['package.xml']),
    ],
    install_requires=['setuptools'],
    zip_safe=True,
    maintainer='robot',
    maintainer_email='robot@todo.todo',
    description='TODO: Package description',
    license='TODO: License declaration',
    tests_require=['pytest'],
    entry_points={
        'console_scripts': [
        'voice = example_python.voice:main',
        'anomaly_detection_publisher = example_python.anomaly_detection_publisher:main',
        'anomaly_detection_publisher_video = example_python.anomaly_detection_publisher_video:main',
        'anomaly_detection_publisher_video_new = example_python.anomaly_detection_publisher_video_new:main',
        'integrated_anomaly_detector = example_python.integrated_anomaly_detector:main',
        'testTTL = example_python.testTTL:main',
        'control8 = example_python.control8:main',
        'odmAndControl = example_python.odmAndControl:main',
        'tele_key = example_python.tele_key:main',
        'turn = example_python.turn:main',
        'my_navToPose = example_python.my_navToPose:main',   
        'controlRobot = example_python.controlRobot:main',
        'detect = example_python.detect:main',   
        'testVosk = example_python.testVosk:main', 
        'robotStatus = example_python.robotStatus:main', 
        'camera = example_python.camera:main',
        'new_nav = example_python.new_nav:main',
        'huofu = example_python.huofu:main',
        'chicken = example_python.chicken:main',
        'video_saver = example_python.video_saver:main',
        'huofu_new = example_python.huofu_new:main',
        'anomaly_detection_publisher_webrtc = example_python.anomaly_detection_publisher_webrtc:main',
        'ultraSensor = example_python.ultraSensor:main',
        'ultraSensorNew = example_python.ultraSensorNew:main',
        'test_TTL = example_python.test_TTL:main',
        'tem = example_python.tem:main',
        'anDetect = example_python.anDetect:main',
        'controlRobot_new = example_python.controlRobot_new:main',
        'testSherpa = example_python.testSherpa:main',
        'followPoints = example_python.followPoints:main',
        'followPointsV2 = example_python.followPointsV2:main',
        'followPointsV3 = example_python.followPointsV3:main',
        'followPointsV4 = example_python.followPointsV4:main',
        'followPointsV5 = example_python.followPointsV5:main',
        'followPointsV6 = example_python.followPointsV6:main',
        'followPointsV7 = example_python.followPointsV7:main',
        'charge = example_python.charge:main',
        'chargeV2 = example_python.chargeV2:main',
        'charge_back = example_python.charge_back:main',
        'followPointsV8 = example_python.followPointsV8:main',
        'ycjc = example_python.ycjc:main',
        'hotCam = example_python.hotCam:main',
        'new_hotCam = example_python.new_hotCam:main',
        'hot_hik = example_python.hot_hik:main',
        'ptz_detect = example_python.ptz_detect:main',
        'radar_z = example_python.radar_z:main',
        'web_hard = example_python.web_hard:main',
        'test_TTL_1 = example_python.test_TTL_1:main',
        'nav_point = example_python.nav_point:main',
        'navpoint1 = example_python.navpoint1:main',
        'navpoint2 = example_python.navpoint2:main',
        'web_hard_1 = example_python.web_hard_1:main',
        'path_deviation_recorder = example_python.path_deviation_recorder:main',
        'path_deviation_viewer = example_python.path_deviation_viewer:main'
        ],
    },
)
